### ISSUE TITLE
L

### ISSUE THREAD

**Issue by cellomonster** [stoozey/sengine#3]
sucks ass

**Comment by stoozey** [comment]
![file_54234bfc-1285-4d19-aaf8-2c1774faec9e 007bd3e64e5c5d7a86d97c2593a3442ae69d04a26e0af56cda14635572007bf3 3 thumbnail-256](https://github.com/stoozey/sengine/assets/25302724/e717dd4f-f120-44c7-b65d-362ad4448048)
